### ISSUE TITLE
axe cli apparently not respecting the --chromedriver-path argument

### ISSUE THREAD

**Issue by macbookandrew** [dequelabs/axe-core-npm#370] opened 2021-09-17 14:19 UTC
Product: cli

Expectation: I expect that using the `--chromedriver-path` to specify a path should work

Actual: It apparently ignores it

Example:

```shell
❯ axe https://example.com --chromedriver-path="/usr/local/Caskroom/chromedriver/93.0.4577.63/chromedriver" --show-errors
Running axe-core 4.3.3 in chrome-headless
Error: "session not created: This version of ChromeDriver only supports Chrome version 90\nCurrent browser version is 93.0.4577.82 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
 $s SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 93.0.4577.82 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    at Object.throwDecodedError (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:643:13)
    at Executor.execute (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:569:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/

# To verify chromedriver version:
❯ /usr/local/Caskroom/chromedriver/93.0.4577.63/chromedriver --version
ChromeDriver 93.0.4577.63 (ff5c0da2ec0adeaed5550e6c7e98417dac77d98a-refs/branch-heads/4577@{#1135})
```

Motivation: I’m just trying to use the CLI 😂 

<pre><code>
axe-core version: 4.3.3
@axe-core/cli: 4.2.2

- Node version: 16.6.1
- Platform: Mac
</code></pre>

**Comment by macbookandrew** [comment] 2021-09-17 14:20
BTW I am getting the same error when I run without the `--chromedriver-path` flag:

```shell
❯ axe https://example.com --show-errors
Running axe-core 4.3.3 in chrome-headless
Error: "session not created: This version of ChromeDriver only supports Chrome version 90\nCurrent browser version is 93.0.4577.82 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
 $s SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 93.0.4577.82 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    at Object.throwDecodedError (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:643:13)
    at Executor.execute (/usr/local/lib/node_modules/@axe-core/cli/node_modules/selenium-webdriver/lib/http.js:569:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Please report the problem to: https://github.com/dequelabs/axe-core-npm/issues/
```

**Comment by Zidious** [comment] 2022-01-10 13:16
Hello All, 

Thanks for submitting this issue. I have opened a PR to resolve using a different Chrome Driver version. However, after some investigation it appears your actual Chrome and Chrome driver have to match other wise this error will occur. For example, I have V96 of Chrome installed and I am able to use V96-97 but I cannot use anything prior to V96 which is what my current Chrome version is. 


> We maintain multiple versions of ChromeDriver. Which version to select depends on the version of Chrome you are using it with. Specifically: 

> ChromeDriver uses the same version number scheme as Chrome. See https://www.chromium.org/developers/version-numbers for more details. Each version of ChromeDriver supports Chrome with matching major, minor, and build version numbers. For example, ChromeDriver 73.0.3683.20 supports all Chrome versions that start with 73.0.3683. Before a new major version of Chrome goes to Beta, a matching version of ChromeDriver will be released. After the initial release of a new major version, we will release patches as needed. These patches may or may not coincide with updates to Chrome.

Source: [chromedriver.chromium.org](https://chromedriver.chromium.org/downloads/version-selection)

**Comment by zacharyFolwick** [comment] 2022-02-02 22:25
This bug is still an issue.  Chrome and chromedriver versions match.

**Comment by Zidious** [comment] 2022-02-03 21:56
Hey @zacharyFolwick, 

Could you please confirm if you have tried the `@next` version of axe-core-npm CLI tool as this includes the fix. The merged PR is not yet been put into a stable release yet.

**Comment by Zidious** [comment] 2022-04-19 18:02
Closing due to inactivity. Please feel free to reopen if the issue is still apparent in 4.4.1.

**Closed by Zidious** 2022-04-19 18:02 UTC
Labels: bug, PR

**Comment by ExplorerSunil** [comment] 2023-07-29 10:49
Its still the same even in 4.7.3. I've downloaded the chrome driver 113 from here: https://chromedriver.chromium.org/downloads and my current google chrome version is 115, but its expecting 113. Whats the point of providing the parameter if the installed browser and driver for testing needs to match anyway. If I downgrade my chrome, then it would be solved automatically.

**Comment by Zidious** [comment] 2023-07-29 16:24
Correct - unfortunately, that is not a limitation of the CLI. Chromedriver requires the Chrome version to patch (or be at least +/- 1).
