### ISSUE TITLE
WebdriverJS axecore binding throws legacy code error

### ISSUE THREAD

**Issue by samiullah** [dequelabs/axe-core-npm#429] opened 2022-01-19 05:45 UTC
Getting following error when I run my test. I am using latest axe core version. Please note i m not doing anything with setting legacy-code flags
`AXE-final (1)\AXE-Automation> node .\WebAccessibility_new.js
D:\AXE-final (1)\AXE-Automation\node_modules\@axe-core\webdriverjs\dist\index.js:57
        this.legacyMode = false;
                        ^

TypeError: Cannot set properties of undefined (setting 'legacyMode')
    at AxeBuilder (D:\AXE-final (1)\AXE-Automation\node_modules\@axe-core\webdriverjs\dist\index.js:57:25)
    at Object.<anonymous> (D:\AXE-final (1)\AXE-Automation\WebAccessibility_new.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47`

**Comment by michael-siek** [comment] 2022-01-25 16:55
Thank you for reporting! We will investigate this issue further and update you as soon as we can.

**Comment by Zidious** [comment] 2022-01-25 18:58
Hey @samiullah, 

Could you please provide a snippet of how you are using WebdriverJS? Using the latest version of axe-core-npm-webdriverjs 4.3.2 I was unable to recreate the issue.

**Comment by andder1** [comment] 2022-02-21 22:23
Hey team - seeing a similar error on my end and was wondering if any update or guidance for a workaround.  Thanks!

`UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'legacyMode' of undefined
    at AxeBuilder (/Users/djand/Sites/testing/web_axp-disputes-js-test/node_modules/@axe-core/webdriverjs/dist/index.js:57:25)`

**Comment by Zidious** [comment] 2022-02-28 15:25
Hey @andder1, 

Apologies for the delay, I believe this was fixed in https://github.com/dequelabs/axe-core-npm/issues/444 and we will be doing a patch release shortly.

**Comment by andder1** [comment] 2022-03-15 21:50
@Zidious appreciate the response!  Is there a timeline on the patch release? (or did I miss it?)

**Comment by michael-siek** [comment] 2022-03-15 21:53
Hi @andder1, It looks like this was released in 4.4.0.

**Comment by Zidious** [comment] 2022-04-19 17:46
Closing due to inactivity, please re-open if the issue is apparent in 4.4.1

**Closed by Zidious** 2022-04-19 17:46 UTC

**Comment by BeginnerQA** [comment] 2022-08-03 08:55
I am getting the same error in the 4.4.3 version.

 TypeError: Cannot set properties of undefined (setting 'legacyMode')
      at AxeBuilder (node_modules\@axe-core\webdriverjs\dist\index.js:57:25)
      at test\AxeSpec.js:78:9
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at node_modules\selenium-webdriver\lib\promise.js:2927:27
      at node_modules\selenium-webdriver\lib\promise.js:668:7
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
