### ISSUE TITLE
4.7.3 version is not running 

### ISSUE THREAD

**Issue by anagritsay** [dequelabs/axe-core-npm#816] opened 2023-09-06 13:33 UTC
### Product

cli

### Product Version

4.7.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

Hello, I installed the last version of axe-core/cli 4.7.3. Instead of the last version, it is running the version 4.7.2, which cause the error, related with the chrome driver.

**Comment by anagritsay** [comment] 2023-09-06 13:49
![image](https://github.com/dequelabs/axe-core-npm/assets/101796180/d59d6a6c-63b8-40e0-90bf-1d0485090f44)

**Comment by Zidious** [comment] 2023-09-06 13:56
This was recently fixed in https://github.com/dequelabs/axe-core-npm/pull/796 we haven't published a stable version just yet. If install the `@next` (`npm install @axe-core/cli@next -g`) version that should resolve your issues.

**Comment by straker** [comment] 2023-09-06 14:32
A newer version of the cli won't necessarily fix the chromedriver issue, but will help push it to the next version. A better solve can be found in https://github.com/dequelabs/axe-core-npm/pull/680 wherein we provide a new error message about how to handle chromedriver version mismatches. You'll need to install chromedriver to the same location as the cli was installed (which is typically globally). Since your chrome version is listed as 115, you'll want that same version of chromedriver.

```
npm i -g chromedriver@115
```

That should fix the issue and allow cli to run again.

**Comment by anagritsay** [comment] 2023-09-06 15:15
Thank you for your answer.

I have set up the chromedriver@115 version
Regarding the --chromedriver-path <url...> - can be anywhere? Or in the specific folder?

Seems that now, using @axe-core/cli@next solved the problem.

**Comment by straker** [comment] 2023-09-06 15:19
Glad the problem is solved.

```
--chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver
```

Technically the chromedriver path can be anywhere, you just need to supply the path to it.

**Comment by padmavemulapati** [comment] 2023-10-11 11:51
Verified with the latest version of @axe-core/cli_4.7.4-62fd241.0` , chromedriver when ever version compatibility error showing, we can have a solution uisng `--chromedriver-path` option.

Steps to validate:

1) To get a updated chromedriver version at the global location
     `npm install chromedriver --update -g`

2) To Find out where chromedriver is  we can use a command at the terminal in MAC -  `which chromedriver` and in windows - `Where chromedriver`

     Which gives you something like this
     `/usr/local/bin/chromedriver` _From a mac_

3) Run axe cli with the following flag. _Based on above step_
     Flag: `--chromedriver-path /usr/local/bin/chromedriver`
     
**Example:**   

```bash
axe  --chromedriver-path /usr/local/bin/chromedriver  https://google.com
```

### Getting more comfortable

```bash
axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://google.com
```

We can see the output successfully, even we have non-compatible version saved in our machine and trying to run `axe-cli` . This above process will update the compatibility version of chromdriver and pick the path from where the compatible version of chromedriver located and working as expected.

Output:

```
axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://google.com
Running axe-core 4.8.2 in chrome-headless

Testing http://google.com ... please wait, this may take a minute.

  Violation of "aria-allowed-role" with 1 occurrences!
    Ensures role attribute has an appropriate value for the element. Correct invalid elements at:
     - #APjFqb
    For details, see: https://dequeuniversity.com/rules/axe/4.8/aria-allowed-role

  Violation of "aria-valid-attr-value" with 2 occurrences!
    Ensures all ARIA attributes have valid values. Correct invalid elements at:
     - #APjFqb
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.8/aria-valid-attr-value

  Violation of "color-contrast" with 8 occurrences!
    Ensures the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds. Correct invalid elements at:
     - .uU7dJb
     - a[data-usg="AOvVaw33zjaJZ_ogw8iPEm4kPGYh"]
     - a[data-usg="AOvVaw3Oj62V1xNd5oAI6Vxou5Lx"]
     - a[data-usg="AOvVaw2SJ4zwRVXKyZr53qG9dm4K"]
     - .pHiOh:nth-child(4)
     - a[data-usg="AOvVaw2y-DJehqHRQuhUzwsARmol"]
     - a[data-usg="AOvVaw25sheD5OGrPUyBw_FdCQOy"]
     - .ayzqOc
    For details, see: https://dequeuniversity.com/rules/axe/4.8/color-contrast

  Violation of "region" with 8 occurrences!
    Ensures all page content is contained by landmarks. Correct invalid elements at:
     - .gb_yd > div:nth-child(1)
     - .gb_za
     - .lnXdpd
     - #SIvCob
     - .uU7dJb
     - .AghGtd
     - a[data-usg="AOvVaw2y-DJehqHRQuhUzwsARmol"]
     - a[data-usg="AOvVaw25sheD5OGrPUyBw_FdCQOy"]
    For details, see: https://dequeuniversity.com/rules/axe/4.8/region

19 Accessibility issues detected.
Testing complete of 1 pages

Please note that only 20% to 50% of all accessibility issues can automatically be detected. 
Manual testing is always required. For more information see:
https://dequeuniversity.com/curriculum/courses/testingmethods
```

### Screenshot:
<img width="951" alt="image" src="https://github.com/dequelabs/axe-core-npm/assets/47409579/d7b2c767-40bc-4657-9312-ea3869f9a30b">

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-npm/react_|
|**Version** | _4.7.4-62fd241.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|

**Closed** 2023-10-11 11:54 UTC
