### ISSUE TITLE
@axe-core/playwright throws an `TypeError: AxeBuilder is not a constructor`  error

### ISSUE THREAD

**Issue by Volubyl** [dequelabs/axe-core-npm#601] opened 2022-11-07 15:40 UTC
Product:  @axe-core/playwright
Expectation: 

Should do something other than throw an `TypeError: AxeBuilder is not a constructor`  error

Actual: 

I followed the [example of accessibility test provided by Playwright](https://playwright.dev/docs/accessibility-testing#example-accessibility-tests) but I ended up with this error 

```
`TypeError: AxeBuilder is not a constructor`
```
The test looks like :

```
import { test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright'; // 1

test.describe('homepage', () => { // 2
  test('should not have any automatically detectable accessibility issues', async ({ page }) => {
    await page.goto('/'); // 3

    try {
        const results = await new AxeBuilder({ page }).analyze();
        console.log(results);
      } catch (e) {
         console.log(e) // TypeError: AxeBuilder is not a constructor
      }
  });
});

```

Motivation: 

Because at the moment I can not use axe core with playwright

 - "@axe-core/playwright": "^4.5.0",
 - "@playwright/test": "^1.27.1",

- Node version: 16.17.1
- Platform:  Linux

**Comment by Volubyl** [comment] 2022-11-09 11:35
I tried to tinker a bit this morning, and at the moment my best guess would be a typescript build "issue".

Maybe something about esm module ?

For the context, I'm working with [SvelteKit](https://kit.svelte.dev/) and I had several issues in the past with ESM modules.

At the moment, I'm only at the beginning of my investigation, so it's only a guess ...

**Comment by Zidious** [comment] 2022-11-09 14:32
Hey @Volubyl, 

Apologies for the delay - we will investigate this issue and get back to you as soon as possible

**Comment by Volubyl** [comment] 2022-11-09 15:23
No worries, I was so glad to learn axe core had a playwright integration. I'll try to go further in this investigation.

I cloned the repo to get a local version of the package and was able to reproduce using `npm link` so I'm ready to contribute ;-)

**Comment by Volubyl** [comment] 2022-11-10 09:42
Ok ... I think you can close this issue. It seems that the issue is not directly related to @axe-core/playwright, but more generally to an ESM/CJS compatibility problem.

Long story short : [Vite](https://vitejs.dev/) (the bundle) "encourage" the use of ESM modules instead of CJS and has sometimes issues to work properly when there is a mix of ESM and CJS module in a single APP.

I noticed the current [axe-core/playwright TS configuration file](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/playwright/tsconfig.json) has the `module` property set to "commonjs".

With that configuration, the library won't be properly usable for people working with ESM modules in certain conditions.

More about this here : https://kit.svelte.dev/faq#packages

Maybe It would be nice if you consider distributing the package both as ESM and CJS. It can be done by modifying the TSconfig.

In my case, I think there are several configuration issues in my project So, that is not a feature request but more a "long term" suggestion.

But If you're interested, I'll be glad to help :ok_hand:

**Comment by einarpersson** [comment] 2022-11-10 12:56
I just stumbled on exactly the same thing. Also using SvelteKit (which is using Vite).

@Volubyl does this mean that you did not find a workaround?

**Comment by Volubyl** [comment] 2022-11-10 13:45
3 hours ago, I would have said yes ... But I made a false joy :(

I removed the line `"type": "module"` from my package.json and after doing this I succeed to launch the test. 

But without the line, the command `npm run build` throws a lot of error. So I think it is not a solution ... :sweat_smile: 

I definitively think the only way to fix this issue would be to distribute "@axe-core/playwright" both as an ESM and CJS package.

Is this possible ? Should I open a specific issue ? @Zidious 

I can work on that this weekend and tomorrow

**Comment by Volubyl** [comment] 2022-11-10 13:46
> Ah, here is a workaround:
> 
> ```ts
>  const accessibilityScanResults = await new AxeBuilder.default({ page }).analyze()
> ```
> 
> It works, but typescript complains _"property 'default' does not exist on type 'typeof AxeBuilder'"_
> 
> Found it here: [microsoft/playwright#18562](https://github.com/microsoft/playwright/issues/18562)

Oh, nice workaround!

**Comment by akornmeier** [comment] 2023-02-15 21:35
Hello Deque friends!

I have also came across this same issue. While building a simple wrapper around @axe-core/playwright in a ViteJS project, I got:

`TypeError: AxeBuilder is not a constructor at ../src/index.ts`

```js
  return new AxeBuilder({ page }).analyze();
```

Is it possible that this is a symptom of only exporting a CommonJS module?

**Comment by akornmeier** [comment] 2023-02-16 16:39
I did a little more research with this issue and I agree with @Volubyl when they stated:

> With that configuration, the library won't be properly usable for people working with ESM modules in certain conditions.

I created a branch and was able to solve the issue ESM issue with a few minor changes. @Zidious @michael-siek - would you like to create a separate issue specifically for distributing @axe-core/playwright for both CJS and ESM? I have a PR ready to submit with these updates.

**Comment by meduzen** [comment] 2023-03-03 18:48
> > Ah, here is a workaround:
> > ```ts
> >  const accessibilityScanResults = await new AxeBuilder.default({ page }).analyze()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works, but typescript complains _"property 'default' does not exist on type 'typeof AxeBuilder'"_
> > Found it here: [microsoft/playwright#18562](https://github.com/microsoft/playwright/issues/18562)
> 
> Oh, nice workaround!

Another workaround allowing for types completion (I’m not using TypeScript but JSDoc + IDE completion):

```js
// index.spec.mjs

import { test, expect } from '@playwright/test'
import AxeCorePlaywright from '@axe-core/playwright'

/** @type {import('@axe-core/playwright').default} */
const AxeBuilder = AxeCorePlaywright.default;

test('It tests something some accessibility stuff', async ({ page }) => {
  const results = await new AxeBuilder({ page }).analyze()

  /**
   * Send Axe results or violations to the JSON report.
   *
   * https://playwright.dev/docs/test-annotations#custom-annotations
   */
  test.info().annotations.push(results);

  await expect(results.violations.length).toBe(0)
})
```

**Comment by Zidious** [comment] 2023-06-01 18:47
👋 Hey all,

This issue should be resolved. Please use `@latest` version. 

Let me know if you run into any issues

**Comment by straker** [comment] 2023-09-11 22:50
Closing as the issue seems to be resolved. Feel free to reopen a new issue if you still are running into this problem.

**Closed by straker** 2023-09-11 22:50 UTC
Labels: PROD: axe-core-npm, TYPE: prod bug, PRIORITY: low, PACKAGE: playwright

**Comment by padmavemulapati** [comment] 2023-09-14 10:07
Not able to reproduce, its working fine
